{
  "Uuid": "3c9d0464-8643-5ffe-96e5-ab1769818209",
  "IsCustomNode": false,
  "Description": "",
  "Name": "CURVE_START_END_POINTS",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "32f7af03377940db9b9eff065528c53a",
      "Inputs": [
        {
          "Id": "9494bc9ae4cd4febabc8045e25cbfcb5",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "ffb34a2be954441499e9953c36076392",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "83fcba3249f040b4a0f5d5716751b08e",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "d1751d65cb2b4f7e808b4691f87a1de2",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "1;",
      "Id": "ef3577e9f89e482f8b8ca9849dfbbe09",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "14d0876337ea419ebb9541e2d6f3c5d9",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Id": "f3e5db5f18a54d2692b3a2b03f154d18",
      "Inputs": [
        {
          "Id": "775bf4319a244c30b4241b852fa1b58b",
          "Name": "startPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "4a98ba6bb15b408ca3b027158863689e",
          "Name": "endPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "77dbeb7861d04638b4eb58390d780608",
          "Name": "Line",
          "Description": "Line",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Creates a straight Line between two input Points.\n\nLine.ByStartPointEndPoint (startPoint: Point, endPoint: Point): Line"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "bc7312386a6a46fb8e6043f546843245",
      "Inputs": [
        {
          "Id": "58411aa24806443bb05af0b78099c0ba",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "ef514b9f5c514a499dcd39772d41a4e8",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "49a6851d7e32457c9b70040de1a8308b",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "927b7082641f4fed9c53f2f45b76af4e",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.StartPoint",
      "Id": "241019c1013445539b128c100dd146ff",
      "Inputs": [
        {
          "Id": "85f4f3b19dc24d81b4bb7335619babd6",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "7927bdac520a418aa0d271c8b119ad61",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the start Point along the Curve\n\nCurve.StartPoint: Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.EndPoint",
      "Id": "9b5cb6baa0ae44e0aa5ae59736e58519",
      "Inputs": [
        {
          "Id": "7040953884da4648a81c2a2f66a5b2ee",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "364575b1b2544c8a9169c6b094763bd7",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the end Point along the Curve\n\nCurve.EndPoint: Point"
    }
  ],
  "Connectors": [
    {
      "Start": "d1751d65cb2b4f7e808b4691f87a1de2",
      "End": "775bf4319a244c30b4241b852fa1b58b",
      "Id": "625b5579455e41098ab21319e129039c"
    },
    {
      "Start": "14d0876337ea419ebb9541e2d6f3c5d9",
      "End": "9494bc9ae4cd4febabc8045e25cbfcb5",
      "Id": "3b5330dbbc734120a1ba1b49c598fc33"
    },
    {
      "Start": "77dbeb7861d04638b4eb58390d780608",
      "End": "85f4f3b19dc24d81b4bb7335619babd6",
      "Id": "0b7392c9d32d4588805189de7d013d80"
    },
    {
      "Start": "77dbeb7861d04638b4eb58390d780608",
      "End": "7040953884da4648a81c2a2f66a5b2ee",
      "Id": "cb31ac5877c842cb85d4294f96355e0c"
    },
    {
      "Start": "927b7082641f4fed9c53f2f45b76af4e",
      "End": "4a98ba6bb15b408ca3b027158863689e",
      "Id": "7d59442a63134ff09daaf790f5007cd6"
    }
  ],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.0.2.6826",
      "RunType": "Automatic",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": 2.0673387050628662,
      "EyeY": 1.6271553039550781,
      "EyeZ": 2.3227789402008057,
      "LookX": -6.7057957649230957,
      "LookY": -1.8246537446975708,
      "LookZ": -7.36682653427124,
      "UpX": 0.023492587730288506,
      "UpY": 0.99939084053039551,
      "UpZ": 0.025808393955230713
    },
    "NodeViews": [
      {
        "ShowGeometry": false,
        "Name": "Point.ByCoordinates",
        "Id": "32f7af03377940db9b9eff065528c53a",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 279.367007290406,
        "Y": 405.901385691001
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "ef3577e9f89e482f8b8ca9849dfbbe09",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 450.736275027205,
        "Y": 594.802976877127
      },
      {
        "ShowGeometry": true,
        "Name": "Line.ByStartPointEndPoint",
        "Id": "f3e5db5f18a54d2692b3a2b03f154d18",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 450.340482072885,
        "Y": 483.098819804126
      },
      {
        "ShowGeometry": false,
        "Name": "Point.ByCoordinates",
        "Id": "bc7312386a6a46fb8e6043f546843245",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 279.52031599546,
        "Y": 543.967676550671
      },
      {
        "ShowGeometry": true,
        "Name": "Curve.StartPoint",
        "Id": "241019c1013445539b128c100dd146ff",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 672.275218688848,
        "Y": 436.769009466787
      },
      {
        "ShowGeometry": true,
        "Name": "Curve.EndPoint",
        "Id": "9b5cb6baa0ae44e0aa5ae59736e58519",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 671.527963683407,
        "Y": 542.131965233961
      }
    ],
    "Annotations": [],
    "X": -328.309220003628,
    "Y": -642.637636151635,
    "Zoom": 1.78359936238281
  }
}