{
  "Uuid": "3c9d0464-8643-5ffe-96e5-ab1769818209",
  "IsCustomNode": false,
  "Description": "",
  "Name": "SURFACE_SINGLE_POINTATPARAMETER_55",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Rectangle.ByWidthLength@double,double",
      "Id": "9655317d0f2541959234a3b64b4dca84",
      "Inputs": [
        {
          "Id": "2c19c592011a4aa184af341e48b63700",
          "Name": "width",
          "Description": "double\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "df209576d0cf459eb0aa90f9e881c33e",
          "Name": "length",
          "Description": "double\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "7e333472b3914cbd94edd33f108d20fd",
          "Name": "Rectangle",
          "Description": "Rectangle",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Rectangle centered at the WCS origin in the WCS XY Plane, with specified width (X Axis length), and length (Y Axis length).\n\nRectangle.ByWidthLength (width: double = 1, length: double = 1): Rectangle"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Surface.ByPatch@Autodesk.DesignScript.Geometry.Curve",
      "Id": "f9c311c1add643b1a6ec85202972744e",
      "Inputs": [
        {
          "Id": "ede5f5993d4e490bbe301543fda34935",
          "Name": "closedCurve",
          "Description": "Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "46be9b0c5f0142be836d6c20d83e6a0d",
          "Name": "Surface",
          "Description": "Surface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Surface by filling in the interior of a closed boundary defined by input Curves.\n\nSurface.ByPatch (closedCurve: Curve): Surface"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Surface.PointAtParameter@double,double",
      "Id": "65a4cf95b1404da8866ef1f4fee08c03",
      "Inputs": [
        {
          "Id": "eb23d98075af48c7add28f4e21f25a12",
          "Name": "surface",
          "Description": "Autodesk.DesignScript.Geometry.Surface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "6b53db853bd04ef8b405590353677036",
          "Name": "u",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "d12e4c095c6242449f72c0f5af62394d",
          "Name": "v",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "b6b2c3486ac04f5395928b0360d290ea",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Return the Point at specified U and V parameters.\n\nSurface.PointAtParameter (u: double = 0, v: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "0.5;\n0.5;",
      "Id": "2ef1697322f84b49b4d45f535924a43d",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "69be49ec758549378bc409d7736fd68a",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2fdf835a04bb4e69b767905a1ab7a420",
          "Name": "",
          "Description": "Value of expression at line 2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    }
  ],
  "Connectors": [
    {
      "Start": "7e333472b3914cbd94edd33f108d20fd",
      "End": "ede5f5993d4e490bbe301543fda34935",
      "Id": "d5ae0372440349c4ab7a232786381831"
    },
    {
      "Start": "46be9b0c5f0142be836d6c20d83e6a0d",
      "End": "eb23d98075af48c7add28f4e21f25a12",
      "Id": "e5b6b54aa4d04323a70ae68c94acefd8"
    },
    {
      "Start": "69be49ec758549378bc409d7736fd68a",
      "End": "6b53db853bd04ef8b405590353677036",
      "Id": "93cf454e6da34e68a7876b96e53d4579"
    },
    {
      "Start": "2fdf835a04bb4e69b767905a1ab7a420",
      "End": "d12e4c095c6242449f72c0f5af62394d",
      "Id": "318f0731411e434b80a10ff87f4f9e5a"
    }
  ],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.0.2.6826",
      "RunType": "Automatic",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": 0.91338914632797241,
      "EyeY": 1.666221022605896,
      "EyeZ": 0.60034960508346558,
      "LookX": -4.6100192070007324,
      "LookY": -5.1551394462585449,
      "LookZ": -2.736072301864624,
      "UpX": -0.44932106137275696,
      "UpY": 0.85264015197753906,
      "UpZ": -0.26667457818984985
    },
    "NodeViews": [
      {
        "ShowGeometry": false,
        "Name": "Rectangle.ByWidthLength",
        "Id": "9655317d0f2541959234a3b64b4dca84",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 299.241760066262,
        "Y": 577.99279283499
      },
      {
        "ShowGeometry": true,
        "Name": "Surface.ByPatch",
        "Id": "f9c311c1add643b1a6ec85202972744e",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 292.653019448316,
        "Y": 498.104516586346
      },
      {
        "ShowGeometry": true,
        "Name": "Surface.PointAtParameter",
        "Id": "65a4cf95b1404da8866ef1f4fee08c03",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 662.283601195263,
        "Y": 498.261941108841
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "2ef1697322f84b49b4d45f535924a43d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 552.783284791177,
        "Y": 531.065003589865
      }
    ],
    "Annotations": [],
    "X": -529.824483928098,
    "Y": -1049.35604407048,
    "Zoom": 2.22719516868276
  }
}