{
  "Uuid": "3c9d0464-8643-5ffe-96e5-ab1769818209",
  "IsCustomNode": false,
  "Description": "",
  "Name": "SOLID_BY_SURFACE_THICKEN1_side",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [
    {
      "Id": "9a76820b9dcc4ad290f2a79e4cb33dda",
      "Name": "Boolean",
      "Type": "boolean",
      "Value": "false",
      "Description": "Selection between a true and false."
    }
  ],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "32f7af03377940db9b9eff065528c53a",
      "Inputs": [
        {
          "Id": "b58eee436f6948cd98f0240d3629bf4b",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "e4a53127661541f1ac18459d43f87c6f",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "7a085e7aa3224bc8a07234c3e1bd816c",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "d7212ed016854a2cb579350a99b71c24",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "1;",
      "Id": "ef3577e9f89e482f8b8ca9849dfbbe09",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "e0f5e1deee464c57bd3a8765f02f4a33",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Id": "f3e5db5f18a54d2692b3a2b03f154d18",
      "Inputs": [
        {
          "Id": "0e20906fab74414ab7c5c5035d9682d8",
          "Name": "startPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "93121ff5b2534d5d9feeccf14a6d46f1",
          "Name": "endPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "f667a9c788bb4f84b03286a49548d3fc",
          "Name": "Line",
          "Description": "Line",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Creates a straight Line between two input Points.\n\nLine.ByStartPointEndPoint (startPoint: Point, endPoint: Point): Line"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "bc7312386a6a46fb8e6043f546843245",
      "Inputs": [
        {
          "Id": "5d4f21415236477ab9cbe604342ac9dc",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "45312c9bac1243eda7f427855635e24a",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "cb85433d700c4678a6ee2b057908f4a9",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "b8fddda8c370409bafb5bac4f8b6f37b",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.Extrude@double",
      "Id": "2cdcc4f855db4ba4b19d4dc7381b7fe6",
      "Inputs": [
        {
          "Id": "b27ef7ce105c486e99be64af5b2bd10f",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "949670d6b4ae4fe08061f02e07c623bf",
          "Name": "distance",
          "Description": "The distance to extrude the curve\n\ndouble\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "430a986794d3480187bb95c435113f01",
          "Name": "Surface",
          "Description": "The extruded Surface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Extrudes a Curve in the normal Vector direction\n\nCurve.Extrude (distance: double = 1): Surface"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Surface.Thicken@double,bool",
      "Id": "6ba3df61c5254a0ba5e4bd0b02e13abb",
      "Inputs": [
        {
          "Id": "1935de1540bb478292ca98b0185a0b7b",
          "Name": "surface",
          "Description": "Autodesk.DesignScript.Geometry.Surface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "1b7ba1f3015e443eb2bbff03475154a7",
          "Name": "thickness",
          "Description": "double\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "594eb6b33b4147b79589d9051c09d8d2",
          "Name": "both_sides",
          "Description": "bool\nDefault value : true",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "aab44a1b28f849599b99522b5108c433",
          "Name": "Solid",
          "Description": "Solid",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Thicken Surface into a Solid, extruding in the direction of Surface normals. If both_sides parameter is true, surface is thickened on both sides.\n\nSurface.Thicken (thickness: double = 1, both_sides: bool = true): Solid"
    },
    {
      "ConcreteType": "CoreNodeModels.Input.BoolSelector, CoreNodeModels",
      "NodeType": "BooleanInputNode",
      "InputValue": false,
      "Id": "9a76820b9dcc4ad290f2a79e4cb33dda",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "42227f9434b24c04915f8c9cabe5870e",
          "Name": "",
          "Description": "Boolean",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Selection between a true and false."
    }
  ],
  "Connectors": [
    {
      "Start": "d7212ed016854a2cb579350a99b71c24",
      "End": "0e20906fab74414ab7c5c5035d9682d8",
      "Id": "3c68fa8fd8a5460db2d5225d68a57d90"
    },
    {
      "Start": "e0f5e1deee464c57bd3a8765f02f4a33",
      "End": "b58eee436f6948cd98f0240d3629bf4b",
      "Id": "5451e2a093084863a0855af875ed2665"
    },
    {
      "Start": "f667a9c788bb4f84b03286a49548d3fc",
      "End": "b27ef7ce105c486e99be64af5b2bd10f",
      "Id": "5d6e6a16a23143859f018275bc63235f"
    },
    {
      "Start": "b8fddda8c370409bafb5bac4f8b6f37b",
      "End": "93121ff5b2534d5d9feeccf14a6d46f1",
      "Id": "9113664162684fa993ad66f745d43ec9"
    },
    {
      "Start": "430a986794d3480187bb95c435113f01",
      "End": "1935de1540bb478292ca98b0185a0b7b",
      "Id": "bee41190bfb64924acfa6a85bbe5fa50"
    },
    {
      "Start": "42227f9434b24c04915f8c9cabe5870e",
      "End": "594eb6b33b4147b79589d9051c09d8d2",
      "Id": "8b63a35722ac4995847b5fe74df32647"
    }
  ],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.0.2.6826",
      "RunType": "Automatic",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -0.84495401382446289,
      "EyeY": 7.0000276565551758,
      "EyeZ": 10.206510543823242,
      "LookX": -10.455267906188965,
      "LookY": -6.585291862487793,
      "LookZ": -7.236701488494873,
      "UpX": -0.21281386911869049,
      "UpY": 0.96592581272125244,
      "UpZ": -0.14730089902877808
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "32f7af03377940db9b9eff065528c53a",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 430.293157526139,
        "Y": 490.782943447505
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "ef3577e9f89e482f8b8ca9849dfbbe09",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 606.040777584048,
        "Y": 670.647278061641
      },
      {
        "ShowGeometry": true,
        "Name": "Line.ByStartPointEndPoint",
        "Id": "f3e5db5f18a54d2692b3a2b03f154d18",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 628.028754648975,
        "Y": 502.287596380441
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "bc7312386a6a46fb8e6043f546843245",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 428.099272300985,
        "Y": 632.782578471645
      },
      {
        "ShowGeometry": true,
        "Name": "Curve.Extrude",
        "Id": "2cdcc4f855db4ba4b19d4dc7381b7fe6",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 838.825562588814,
        "Y": 501.870833021807
      },
      {
        "ShowGeometry": true,
        "Name": "Surface.Thicken",
        "Id": "6ba3df61c5254a0ba5e4bd0b02e13abb",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1206.53246828322,
        "Y": 502.29170800229
      },
      {
        "ShowGeometry": true,
        "Name": "Boolean",
        "Id": "9a76820b9dcc4ad290f2a79e4cb33dda",
        "IsSetAsInput": true,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1060.87417778365,
        "Y": 555.747795619617
      }
    ],
    "Annotations": [],
    "X": -489.51319755143,
    "Y": -444.171016017645,
    "Zoom": 1.44324244583205
  }
}