{
  "Uuid": "3c9d0464-8643-5ffe-96e5-ab1769818209",
  "IsCustomNode": false,
  "Description": "",
  "Name": "SURFACE_MULTIPLE_POINTATPARAMETER_LACE_LONG",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Rectangle.ByWidthLength@double,double",
      "Id": "9655317d0f2541959234a3b64b4dca84",
      "Inputs": [
        {
          "Id": "b6d925ac74ae4309ae866966adf99195",
          "Name": "width",
          "Description": "double\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "8c978ce1d6354452a16624c7ee9e73ba",
          "Name": "length",
          "Description": "double\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "adf288a8e1cf42fcbcdcff395f4e65ec",
          "Name": "Rectangle",
          "Description": "Rectangle",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Rectangle centered at the WCS origin in the WCS XY Plane, with specified width (X Axis length), and length (Y Axis length).\n\nRectangle.ByWidthLength (width: double = 1, length: double = 1): Rectangle"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Surface.ByPatch@Autodesk.DesignScript.Geometry.Curve",
      "Id": "f9c311c1add643b1a6ec85202972744e",
      "Inputs": [
        {
          "Id": "95ad2aef220a418d92233c8765c381ff",
          "Name": "closedCurve",
          "Description": "Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "85338a06579647bc9b0dbcaf1b4fa9c1",
          "Name": "Surface",
          "Description": "Surface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Surface by filling in the interior of a closed boundary defined by input Curves.\n\nSurface.ByPatch (closedCurve: Curve): Surface"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Surface.PointAtParameter@double,double",
      "Id": "65a4cf95b1404da8866ef1f4fee08c03",
      "Inputs": [
        {
          "Id": "eaf7294ce38c40378efef9c4e46ba965",
          "Name": "surface",
          "Description": "Autodesk.DesignScript.Geometry.Surface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b85154efaf4d418398a18c7a218cc074",
          "Name": "u",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "507427ed0b9d43b1b9e441f063053eb2",
          "Name": "v",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "12da5cc64bdb426fa624772834a0a04f",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "CrossProduct",
      "Description": "Return the Point at specified U and V parameters.\n\nSurface.PointAtParameter (u: double = 0, v: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "0..1..0.1;",
      "Id": "bfaac93023b34044a90b5caac97eab22",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "99910095ce0e4b4a8e3ffb60ea38e0b9",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    }
  ],
  "Connectors": [
    {
      "Start": "adf288a8e1cf42fcbcdcff395f4e65ec",
      "End": "95ad2aef220a418d92233c8765c381ff",
      "Id": "c0c0e9c7f0374792820caf50a5ad26e0"
    },
    {
      "Start": "85338a06579647bc9b0dbcaf1b4fa9c1",
      "End": "eaf7294ce38c40378efef9c4e46ba965",
      "Id": "e8ac5cf97bef48f9911186806caf2808"
    },
    {
      "Start": "99910095ce0e4b4a8e3ffb60ea38e0b9",
      "End": "b85154efaf4d418398a18c7a218cc074",
      "Id": "0999cf70fff34f58b7c687583b0d3eb5"
    },
    {
      "Start": "99910095ce0e4b4a8e3ffb60ea38e0b9",
      "End": "507427ed0b9d43b1b9e441f063053eb2",
      "Id": "4a8266901f90448cb79d196d78685fa2"
    }
  ],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.0.2.6826",
      "RunType": "Automatic",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": 0.79963374137878418,
      "EyeY": 0.62305283546447754,
      "EyeZ": 0.50252366065979,
      "LookX": -4.0958137512207031,
      "LookY": -4.5801305770874023,
      "LookZ": -2.4308884143829346,
      "UpX": -0.44932106137275696,
      "UpY": 0.85264015197753906,
      "UpZ": -0.26667457818984985
    },
    "NodeViews": [
      {
        "ShowGeometry": false,
        "Name": "Rectangle.ByWidthLength",
        "Id": "9655317d0f2541959234a3b64b4dca84",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 299.241760066262,
        "Y": 577.99279283499
      },
      {
        "ShowGeometry": true,
        "Name": "Surface.ByPatch",
        "Id": "f9c311c1add643b1a6ec85202972744e",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 292.653019448316,
        "Y": 498.104516586346
      },
      {
        "ShowGeometry": true,
        "Name": "Surface.PointAtParameter",
        "Id": "65a4cf95b1404da8866ef1f4fee08c03",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 684.493847510267,
        "Y": 497.316824244373
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "bfaac93023b34044a90b5caac97eab22",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 552.09244909974,
        "Y": 542.368951745713
      }
    ],
    "Annotations": [],
    "X": 895.293040400013,
    "Y": -1038.04740313155,
    "Zoom": 2.11614042156077
  }
}