{
  "Uuid": "d1c30ed6-42b3-4bf7-9bdb-ce19e5305d5a",
  "IsCustomNode": false,
  "Description": null,
  "Name": "WritetoRevit",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Element.SetParameterByName@string,var",
      "Id": "b5e3174f3cc344979cbe1c4d14e20fac",
      "Inputs": [
        {
          "Id": "ede282aab2a447189502792ac6373ef7",
          "Name": "element",
          "Description": "Revit.Elements.Element",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "1abe249e95f34d5ca60c7f95a361d455",
          "Name": "parameterName",
          "Description": "The name of the parameter to set.\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "ff44705484374f82951b1780eeddd74b",
          "Name": "value",
          "Description": "The value.\n\nvar",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "8e67a5c964c44ea7b6f37b48e5de6819",
          "Name": "Element",
          "Description": "Element",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Set one of the element's parameters.\n\nElement.SetParameterByName (parameterName: string, value: var): Element"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Room.ByLocation@Revit.Elements.Level,Autodesk.DesignScript.Geometry.Point,string,string",
      "Id": "e2cbb0cbe31e47f0925ef0004d582cfa",
      "Inputs": [
        {
          "Id": "4d31ed59de8e4b4eb28a54112828bc00",
          "Name": "level",
          "Description": "Level the room is hosted on\n\nLevel",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "920cef708ed94e3086693b4e68212646",
          "Name": "location",
          "Description": "Location for the center of the room\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "ec2660cca4434b3d9ffad4171bca5f47",
          "Name": "name",
          "Description": "Room name\n\nstring\nDefault value : \"\"",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "7a9c0c0f54624d76b833bf371b8a409f",
          "Name": "number",
          "Description": "Room number\n\nstring\nDefault value : \"\"",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "8f43d27253ed4b91935a10c128c37600",
          "Name": "Room",
          "Description": "Room",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Revit Room Element\n\nRoom.ByLocation (level: Level, location: Point, name: string = \"\", number: string = \"\"): Room"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Level.ByElevation@double",
      "Id": "fd4486da196b48998e703303ba3604aa",
      "Inputs": [
        {
          "Id": "8bf26106119841f3aea8ddfbfcfa345b",
          "Name": "elevation",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "6492fc014868426c8743ecbfdd27f926",
          "Name": "Level",
          "Description": "Level",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Revit Level given it's elevation. The name will be whatever Revit gives it.\n\nLevel.ByElevation (elevation: double): Level"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Level.ByElevationAndName@double,string",
      "Id": "b0061c04fc8a43fabbfa0ba238e2aa1b",
      "Inputs": [
        {
          "Id": "313b504183f742cb888c7d48e1cc0a56",
          "Name": "elevation",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "ba0ecfc83c77440e96a270177c526cad",
          "Name": "name",
          "Description": "string",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "df15a1e7baab4d32b674b2c805198a3b",
          "Name": "Level",
          "Description": "Level",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Revit Level given it's elevation and name in the project\n\nLevel.ByElevationAndName (elevation: double, name: string): Level"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Level.ByLevelAndOffset@Revit.Elements.Level,double",
      "Id": "a451c166eeb345feac2311385445fade",
      "Inputs": [
        {
          "Id": "d9a2ef863e254718bbdf27aa261c8ba6",
          "Name": "level",
          "Description": "Level",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "ee8dcfb81dff4628b023ed6c4831c795",
          "Name": "offset",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "f530845ef8614fe8a02cb414e38e1848",
          "Name": "Level",
          "Description": "Level",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Revit Level given it's length offset from an existing level\n\nLevel.ByLevelAndOffset (level: Level, offset: double): Level"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Level.ByLevelOffsetAndName@Revit.Elements.Level,double,string",
      "Id": "ac70e6f04da74d7bb6a23ada2db04f50",
      "Inputs": [
        {
          "Id": "d4600f3959df4e3a8b5ddde80d7ac20c",
          "Name": "level",
          "Description": "Level",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "8a720fb7beda41c198894642b14d3afb",
          "Name": "offset",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "e267b175fae741f2b4542024a0c2cdf5",
          "Name": "name",
          "Description": "string",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "38e68ffc2be24b36bdfc9c969d869f57",
          "Name": "Level",
          "Description": "Level",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Revit Level given a distance offset from an existing level and a name for the new level\n\nLevel.ByLevelOffsetAndName (level: Level, offset: double, name: string): Level"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Room.SetName@string",
      "Id": "f409b73bd4bb4eceb82aec3242e2c93f",
      "Inputs": [
        {
          "Id": "6edca25239c243d89d91529846eca930",
          "Name": "room",
          "Description": "Revit.Elements.Room",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "6115be52da7941a08059ede21c9ee2d3",
          "Name": "value",
          "Description": "Name\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "6d09b2308776440298bc5ef5d9f191c1",
          "Name": "void",
          "Description": "void",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Set name\n\nRoom.SetName (value: string): void"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Room.SetNumber@string",
      "Id": "d2a42998df1344cba4cfb77457cc617e",
      "Inputs": [
        {
          "Id": "8f177cab215d4fdf84b161c41dd9cfda",
          "Name": "room",
          "Description": "Revit.Elements.Room",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "83b4c23d0dc14d848042ef77d8eecd59",
          "Name": "value",
          "Description": "Number\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "a589a964e9744cba915ca9bc6e4a54b0",
          "Name": "void",
          "Description": "void",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Set number\n\nRoom.SetNumber (value: string): void"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Parameter.ParameterByName@Revit.Elements.Element,string",
      "Id": "4dfb48d0881642bc95f07f8d5257a0bb",
      "Inputs": [
        {
          "Id": "3eca799199604a598eaa7b50f7492ba1",
          "Name": "element",
          "Description": "Element\n\nElement",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "17ab7f8e83a64175b0f78bd67e684afe",
          "Name": "name",
          "Description": "Parameter Name\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "68c475a9ef4542aeafd215dda073088d",
          "Name": "Parameter",
          "Description": "Parameter",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get Element's Parameter by Name\n\nParameter.ParameterByName (element: Element, name: string): Parameter"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Parameter.CreateProjectParameter@string,string,string,string,bool,Revit.Elements.Category[]",
      "Id": "1d23aac1c6d64936822a1a479e223b1f",
      "Inputs": [
        {
          "Id": "2f08d01a76fa43efa469a2b14f3c0214",
          "Name": "parameterName",
          "Description": "Name\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2ca19a415bf245168a26bfd7a64ac751",
          "Name": "groupName",
          "Description": "Group of the parameter for shared parameters\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "549e3b3f41964e3a9e4dc2ca39a002a6",
          "Name": "type",
          "Description": "Parameter Type\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "ed79def50a164163a574638b30bc7080",
          "Name": "group",
          "Description": "Parameter Group\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "34f6e11cd6364583890aa0e340220e15",
          "Name": "instance",
          "Description": "Is instance parameter, otherwise it's a type parameter\n\nbool",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "3a32c325489742c195380fe5bc6746ee",
          "Name": "categoryList",
          "Description": "Category[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "a9440936c0a24b12891a3ac9ff9b03a6",
          "Name": "void",
          "Description": "void",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a new Project Parameter in this current Revit document for all applicable categories\n\nParameter.CreateProjectParameter (parameterName: string, groupName: string, type: string, group: string, instance: bool, categoryList: Category[]): void"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Parameter.CreateProjectParameterForAllCategories@string,string,string,string,bool",
      "Id": "8347ac530a7e4e85b82ed5a57246e6db",
      "Inputs": [
        {
          "Id": "e15a7444e48748a9a52c7b401e419700",
          "Name": "parameterName",
          "Description": "Name\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "31a4f4b6e41a43e1babf7aa553e0056c",
          "Name": "groupName",
          "Description": "Group of the parameter for shared parameters\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "497dcc4c1d28435c932ee83ed07d3be3",
          "Name": "type",
          "Description": "Parameter Type\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "ba0d467d261e4e14b3fb3bd5bceeb22b",
          "Name": "group",
          "Description": "Parameter Group\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "59d5890679134c6da27e43ccf5efb809",
          "Name": "instance",
          "Description": "Is instance parameter, otherwise it's a type parameter\n\nbool",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "3fafc972971843d7ae7967385d37abc0",
          "Name": "void",
          "Description": "void",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a new Project Parameter in this current Revit document for all applicable categories\n\nParameter.CreateProjectParameterForAllCategories (parameterName: string, groupName: string, type: string, group: string, instance: bool): void"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Parameter.CreateSharedParameter@string,string,string,string,bool,Revit.Elements.Category[]",
      "Id": "d9c9b5ee127c4b81aec6c09ba663b07c",
      "Inputs": [
        {
          "Id": "eeecaaacb68b470a836193a23aa19209",
          "Name": "parameterName",
          "Description": "Name\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "a8469e94637f4bcb97dd3fd26721e5b5",
          "Name": "groupName",
          "Description": "Group of the parameter for shared parameters\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "8f21244d6b6347bd886c6dd818627af0",
          "Name": "type",
          "Description": "Parameter Type\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f0aca2d146164416954a20d9b6e0c2c4",
          "Name": "group",
          "Description": "Parameter Group\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "658d958e9b1a4661a3631ce2826782f2",
          "Name": "instance",
          "Description": "Is instance parameter, otherwise it's a type parameter\n\nbool",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "16922e59bcef4d2885140e2237437490",
          "Name": "categoryList",
          "Description": "Category[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "ed50d032137b4e979aa11c84a575f83d",
          "Name": "void",
          "Description": "void",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a new Shared Parameter in the current Revit document for all applicable categories\n\nParameter.CreateSharedParameter (parameterName: string, groupName: string, type: string, group: string, instance: bool, categoryList: Category[]): void"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Parameter.CreateSharedParameterForAllCategories@string,string,string,string,bool",
      "Id": "e71598c943bc4ebda6bed47d77b96e74",
      "Inputs": [
        {
          "Id": "f6531b90c64a423780f4378143076f2d",
          "Name": "parameterName",
          "Description": "Name\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "a57c66adb3a2410499e600e75ebf5317",
          "Name": "groupName",
          "Description": "Group of the parameter for shared parameters\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "8d0f30cd8a2c4fd4aa6a24d866a75d95",
          "Name": "type",
          "Description": "Parameter Type\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "6c2251ed4b1549f6b4256268ed89f262",
          "Name": "group",
          "Description": "Parameter Group\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "bf6b0b11864049649cb7d82ddd66ce1d",
          "Name": "instance",
          "Description": "Is instance parameter, otherwise it's a type parameter\n\nbool",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "2d44df82c00542abab3ba3699ec5a427",
          "Name": "void",
          "Description": "void",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a new Shared Parameter in the current Revit document for all applicable categories\n\nParameter.CreateSharedParameterForAllCategories (parameterName: string, groupName: string, type: string, group: string, instance: bool): void"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Parameter.SetValue@Revit.Elements.Parameter,var",
      "Id": "91cce361e63c4cd48af57e7a5bdfafcf",
      "Inputs": [
        {
          "Id": "a7b25d9e5a0a4d278237537fff90ca83",
          "Name": "parameter",
          "Description": "Parameter",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "9c95830674394271b545102318080a2a",
          "Name": "value",
          "Description": "var",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "af17e090853b441d93da1401cd1c7d58",
          "Name": "void",
          "Description": "void",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Set the value of the parameter\n\nParameter.SetValue (parameter: Parameter, value: var): void"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Wall.ByCurveAndHeight@Autodesk.DesignScript.Geometry.Curve,double,Revit.Elements.Level,Revit.Elements.WallType",
      "Id": "beae8d060eda4bf481c32f18ad8a03eb",
      "Inputs": [
        {
          "Id": "b8db8eb9e999491796e0d4ae8f124928",
          "Name": "curve",
          "Description": "Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "39f7d113a2b845578d3d1a3c7711746a",
          "Name": "height",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "40a70f5f51cf401c999d4b7edd9df4e5",
          "Name": "level",
          "Description": "Level",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "4da41d906fdb44939c9e3ec8062dec64",
          "Name": "wallType",
          "Description": "WallType",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "3973bd0731f44423ac30ae120955b57b",
          "Name": "Wall",
          "Description": "Wall",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Revit Wall from a guiding Curve, height, Level, and WallType\n\nWall.ByCurveAndHeight (curve: Curve, height: double, level: Level, wallType: WallType): Wall"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Wall.ByCurveAndLevels@Autodesk.DesignScript.Geometry.Curve,Revit.Elements.Level,Revit.Elements.Level,Revit.Elements.WallType",
      "Id": "53dccb613363435da79f33b702f9a6e8",
      "Inputs": [
        {
          "Id": "465535578cd24d6cad2d0ce235aa33f1",
          "Name": "c",
          "Description": "Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "0d15e4cb4a3145029b2392816ba282fe",
          "Name": "startLevel",
          "Description": "Level",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f0e45f7b6a404f6e9768d1b85959decd",
          "Name": "endLevel",
          "Description": "Level",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "fe7c9ab23be045549360046ff1807304",
          "Name": "wallType",
          "Description": "WallType",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "d3ce9f5d628b4543a4444f26b9db8d5b",
          "Name": "Wall",
          "Description": "Wall",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Revit Wall from a guiding Curve, start Level, end Level, and WallType\n\nWall.ByCurveAndLevels (c: Curve, startLevel: Level, endLevel: Level, wallType: WallType): Wall"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Views.Sheet.ByNameNumberTitleBlockAndView@string,string,Revit.Elements.FamilyType,Revit.Elements.Views.View",
      "Id": "0fcea3e831214deeae8ff01e8c132302",
      "Inputs": [
        {
          "Id": "ccfca141ee4a4b19b46045baa597f5a2",
          "Name": "sheetName",
          "Description": "Sheet Name as String.\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "c847a60c93bc48e49ec14abe2e79c0e4",
          "Name": "sheetNumber",
          "Description": "Sheet Number as String.\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "e6e0bca8cfa740c29004f075b4c39b11",
          "Name": "titleBlockFamilyType",
          "Description": "Titleblock that will be assigned to created Sheet.\n\nFamilyType",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "db66229de79a4f5e82a9f997404ecedd",
          "Name": "view",
          "Description": "Views to be placed on Sheet.\n\nView",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "2b2350ce16c2445bbb92d6c412a86285",
          "Name": "Sheet",
          "Description": "Sheet",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Revit Sheet by the sheet name, number, a title block FamilyType, and a collection of views. This method will automatically pack the view onto the sheet.\n\nSheet.ByNameNumberTitleBlockAndView (sheetName: string, sheetNumber: string, titleBlockFamilyType: FamilyType, view: View): Sheet"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Views.Sheet.ByNameNumberTitleBlockAndViews@string,string,Revit.Elements.FamilyType,Revit.Elements.Views.View[]",
      "Id": "b0767bb0d4f5475d8ac16647e35f7804",
      "Inputs": [
        {
          "Id": "ee11fb52c09a4d5aa57c800eec039026",
          "Name": "sheetName",
          "Description": "Sheet Name as String.\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "bef25dbd89dc424db01305bbe3772a9d",
          "Name": "sheetNumber",
          "Description": "Sheet Number as String.\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "6da4bf681e06418db76fc3603124920c",
          "Name": "titleBlockFamilyType",
          "Description": "Titleblock that will be assigned to created Sheet.\n\nFamilyType",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "34749d5fa87c4170aeb5f492a2dc2106",
          "Name": "views",
          "Description": "Views to be placed on Sheet.\n\nView[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "b3aeae5cb82d462aa46879b35da1f884",
          "Name": "Sheet",
          "Description": "Sheet",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Revit Sheet by the sheet name, number, a title block FamilyType, and a collection of views. This method will automatically pack the views onto the sheet.\n\nSheet.ByNameNumberTitleBlockAndViews (sheetName: string, sheetNumber: string, titleBlockFamilyType: FamilyType, views: View[]): Sheet"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Views.AreaPlanView.ByLevelAndAreaScheme@Revit.Elements.Level,Revit.Elements.Element",
      "Id": "3264028964ff4624a2e2293bc661c765",
      "Inputs": [
        {
          "Id": "41784c9dcff3422c9f02adf2101d1e9f",
          "Name": "level",
          "Description": "The Level on which the AreaPlanView is based.\n\nLevel",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "eae247bccf7f40a8b817d31df0897332",
          "Name": "areaScheme",
          "Description": "Area Scheme to be applied to plan view.\n\nElement",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "c4d0ae9f7eb44eddb4f13fb96d938cc6",
          "Name": "AreaPlanView",
          "Description": "An Area Plan View if successful.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create an Area Plan View at the given Level.\n\nAreaPlanView.ByLevelAndAreaScheme (level: Level, areaScheme: Element): AreaPlanView"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Views.AxonometricView.ByEyePointAndTarget@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point,string",
      "Id": "0cfc0dad6a8646cdabbcb1f33350c01f",
      "Inputs": [
        {
          "Id": "e76e737af1794d42af415d0fc95a5960",
          "Name": "eyePoint",
          "Description": "A Point representing the eye point in meters.\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f26f9fdbf7e04fbc8379e6d3f29f4b93",
          "Name": "target",
          "Description": "A Point representing the target of view in meters.\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "69b02c10d7f3473db6a131e5b1a50e1d",
          "Name": "name",
          "Description": "The name of the view.\n\nstring\nDefault value : \"dynamo3D\"",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "3afd277bb33a43d49b349527b0322bef",
          "Name": "AxonometricView",
          "Description": "An AxonometricView object.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Revit Axonometric (isometric) View from an eye position and a target position.\n\nAxonometricView.ByEyePointAndTarget (eyePoint: Point, target: Point, name: string = \"dynamo3D\"): AxonometricView"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Views.AxonometricView.ByEyePointTargetAndBoundingBox@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.BoundingBox,string,bool",
      "Id": "ecf3cf97b31e453c8c3e5754aacaf395",
      "Inputs": [
        {
          "Id": "35c061510ac445ab8bf9350733350da0",
          "Name": "eyePoint",
          "Description": "A Point representing the eye point.\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "fb8ac104c6ca4f18b20c2d151e71e826",
          "Name": "target",
          "Description": "A Point representing the target of view.\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "eb67771840e64c938141c637b4cdf2bc",
          "Name": "boundingBox",
          "Description": "A BoundingBox. The view will be cropped to this bounding box\n\nBoundingBox",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "ab16dea4d23148ca9d481db2471b0abe",
          "Name": "name",
          "Description": "The name of the view.\n\nstring\nDefault value : \"dynamo3D\"",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "511e1d6543124efbb9d137a76b2fe11a",
          "Name": "isolateElement",
          "Description": "If this argument is set to true, the element or bounding box will be isolated in the current view by creating a minimum size crop box around it.\n\nbool\nDefault value : false",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "eea3f31c04154b6ba6b795d7e850cdfd",
          "Name": "AxonometricView",
          "Description": "An AxonometricView object.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Revit Axonometric (isometric) View from an Eye position and target position and Bounding Box\n\nAxonometricView.ByEyePointTargetAndBoundingBox (eyePoint: Point, target: Point, boundingBox: BoundingBox, name: string = \"dynamo3D\", isolateElement: bool = false): AxonometricView"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Views.AxonometricView.ByEyePointTargetAndElement@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point,string,Revit.Elements.Element,bool",
      "Id": "aa705ca1aa414508a4bc51518b1e5e11",
      "Inputs": [
        {
          "Id": "71c17f2b74b1401b89a0aa537545d178",
          "Name": "eyePoint",
          "Description": "A Point representing the eye point.\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "86145dea18094bcba2c8763f1e3da58f",
          "Name": "target",
          "Description": "A Point representing the target of view.\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "5d2bc58948644d77b9dd10c58c8aa592",
          "Name": "name",
          "Description": "The name of the view.\n\nstring\nDefault value : \"dynamo3D\"",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2b00c3e9d65c4677b5cd4b8bc37293e9",
          "Name": "element",
          "Description": "This argument cannot be null, and it has to be either a Revit.Elements.Element or Revit.GeometryObjectsBoundingBox.\n\nElement",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "0a70dc4631d54d2d9b99cb48fc4d5d2f",
          "Name": "isolateElement",
          "Description": "If this argument is set to true, the element or bounding box will be isolated in the current view by creating a minimum size crop box around it.\n\nbool\nDefault value : false",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "889128594d79403b8232c5a36ff1df6f",
          "Name": "AxonometricView",
          "Description": "An AxonometricView object.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Revit Axonometric (isometric) View from an Eye position and target position and Element\n\nAxonometricView.ByEyePointTargetAndElement (eyePoint: Point, target: Point, name: string = \"dynamo3D\", element: Element, isolateElement: bool = false): AxonometricView"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Views.CeilingPlanView.ByLevel@Revit.Elements.Level",
      "Id": "c7349a20edd44714826f59e10e481702",
      "Inputs": [
        {
          "Id": "cbd72439291e4fa38f1a03abdb553f1d",
          "Name": "level",
          "Description": "Level",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "f992aca3e744438e9bbab0903d7fb949",
          "Name": "CeilingPlanView",
          "Description": "CeilingPlanView",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Revit Floor Plan at a given Level\n\nCeilingPlanView.ByLevel (level: Level): CeilingPlanView"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Views.DraftingView.ByName@string",
      "Id": "16b74724d86742b6b6256e36c0acb5d6",
      "Inputs": [
        {
          "Id": "d97cc8a6690a4020ab7286803df4df91",
          "Name": "name",
          "Description": "Name of the view\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "25cc255a954243a2b5d4b831b6504397",
          "Name": "DraftingView",
          "Description": "The view",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Revit DraftingView given it's name\n\nDraftingView.ByName (name: string): DraftingView"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Views.FloorPlanView.ByLevel@Revit.Elements.Level",
      "Id": "bf37965bc34342adb321d9372c132695",
      "Inputs": [
        {
          "Id": "f5d80e3c585c40eebb4089340297c9ff",
          "Name": "level",
          "Description": "Level",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "91a7774dff0b409c9d01a0e9e33d6ed8",
          "Name": "FloorPlanView",
          "Description": "FloorPlanView",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Revit Floor Plan at a given Level\n\nFloorPlanView.ByLevel (level: Level): FloorPlanView"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Views.PerspectiveView.ByEyePointAndTarget@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point,var,string,bool",
      "Id": "f2dd359798264ebeab9e8c4fbc0022e6",
      "Inputs": [
        {
          "Id": "089d8c1800d14ae7a86f184871d15c0b",
          "Name": "eyePoint",
          "Description": "A Point representing the eye point.\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "3d18176100c149398d54c86176a2ea4b",
          "Name": "target",
          "Description": "A Point representing the target of view.\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "32a188b1edc14af38f7e6a8762645a86",
          "Name": "element",
          "Description": "This argument cannot be null, and it has to be either a Revit.Elements.Element or Revit.GeometryObjectsBoundingBox.\n\nvar",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2f0ef7b7ca984dbb8b2c53791600df7d",
          "Name": "name",
          "Description": "The name of the view.\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "d3b595d1aeb24b908635e0b56ec02c40",
          "Name": "isolateElement",
          "Description": "If this argument is set to true, the element or bounding box will be isolated in the current view by creating a minimum size crop box around it.\n\nbool",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "4c8a2a0c400147688b44a7e8298c7dca",
          "Name": "PerspectiveView",
          "Description": "Returns the resulting PerspectiveView object.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Revit Perspective View from an Eye position, a target position, and either an Element or BoundingBox.\n\nPerspectiveView.ByEyePointAndTarget (eyePoint: Point, target: Point, element: var, name: string, isolateElement: bool): PerspectiveView"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Views.PerspectiveView.ByEyePointTargetAndBoundingBox@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.BoundingBox,string,bool",
      "Id": "1d7ab1ee5d3b4b568c3cb38c1007e527",
      "Inputs": [
        {
          "Id": "60543eed2f134563a921ab111adb2200",
          "Name": "eyePoint",
          "Description": "Eye point in meters\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "fd088c6e6b114fb9b3b971619b188373",
          "Name": "target",
          "Description": "Target of view in meters\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2c8984c44e6445b69c1d79b09d2bf3bf",
          "Name": "boundingBox",
          "Description": "Bounding box represented in meters\n\nBoundingBox",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b710ad95259641faa521cfc29581712e",
          "Name": "name",
          "Description": "string",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "93a2b970f36d4a70819360ad97d9cdb6",
          "Name": "isolateElement",
          "Description": "bool",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "18bccfb9ce3a48d9b1e0ff4b4860cb68",
          "Name": "PerspectiveView",
          "Description": "PerspectiveView",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Revit Perspective View from an Eye position and target position and Bounding Box\n\nPerspectiveView.ByEyePointTargetAndBoundingBox (eyePoint: Point, target: Point, boundingBox: BoundingBox, name: string, isolateElement: bool): PerspectiveView"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Views.PerspectiveView.ByEyePointTargetAndElement@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point,Revit.Elements.Element,string,bool",
      "Id": "033ddb9d9f3f404081b13142d4c4ac2b",
      "Inputs": [
        {
          "Id": "c7d31ea0a4d845eb81fb88712ff3cd36",
          "Name": "eyePoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "5c108a72d759410bbd417f5673094552",
          "Name": "target",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "30d496acf450400da47880cd0b832894",
          "Name": "element",
          "Description": "Element",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "4d297933a1aa4c26ad2d616af70bdbcf",
          "Name": "name",
          "Description": "string",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "4e4d36fcd6d24ebaba5426557dc277bc",
          "Name": "isolateElement",
          "Description": "bool",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "7efbcd9fc506461db46a8f878f2b04a1",
          "Name": "PerspectiveView",
          "Description": "PerspectiveView",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Revit Perspective View from an Eye position and target position and Element\n\nPerspectiveView.ByEyePointTargetAndElement (eyePoint: Point, target: Point, element: Element, name: string, isolateElement: bool): PerspectiveView"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Views.SectionView.ByBoundingBox@Autodesk.DesignScript.Geometry.BoundingBox",
      "Id": "781520ee127a40caa92c5e9e34f39012",
      "Inputs": [
        {
          "Id": "540f7138f9f7470d98e59baf1e4756d3",
          "Name": "box",
          "Description": "The bounding box of the view in meters\n\nBoundingBox",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "c03afe35e8ab4ee0a27ffe83ac5e2c74",
          "Name": "SectionView",
          "Description": "SectionView",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Revit ViewSection by a bounding box\n\nSectionView.ByBoundingBox (box: BoundingBox): SectionView"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Views.SectionView.ByCoordinateSystemMinPointMaxPoint@Autodesk.DesignScript.Geometry.CoordinateSystem,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Id": "46b04a41a44e4871a83e188ecf4befc8",
      "Inputs": [
        {
          "Id": "f5be9484c3d2473eb9ad67b56857f745",
          "Name": "cs",
          "Description": "CoordinateSystem",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "87d24b701f254046bf315067730d238d",
          "Name": "minPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "86720230cecd4a8896daee75568cb4de",
          "Name": "maxPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "2eb8aa0012f34d4ab28fb75a3f410830",
          "Name": "SectionView",
          "Description": "SectionView",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Creates a Revit ViewSection by a specified corrdinate system, minPoint and maxPoint\n\nSectionView.ByCoordinateSystemMinPointMaxPoint (cs: CoordinateSystem, minPoint: Point, maxPoint: Point): SectionView"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Views.StructuralPlanView.ByLevel@Revit.Elements.Level",
      "Id": "f9e81c00248b488597690fbd5df0d8f7",
      "Inputs": [
        {
          "Id": "8c6d8f85594a405e8d9c97418bdbc41c",
          "Name": "level",
          "Description": "The Level on which the StructuralPlanView is based.\n\nLevel",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "61c15c87bcd34d318cfd218fc8d20e34",
          "Name": "StructuralPlanView",
          "Description": "A StructuralPlanView if successful.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Structural Plan View at the given Level.\n\nStructuralPlanView.ByLevel (level: Level): StructuralPlanView"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Views.View3D.CreateUniqueViewName@string",
      "Id": "7ee41da73d784b0a917fd73cc889fabf",
      "Inputs": [
        {
          "Id": "b77a4fcbc6d14fdcb35e595bea281c70",
          "Name": "name",
          "Description": "string",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "6bf8a5a5a8ae4c3395ed44bddcc165d7",
          "Name": "string",
          "Description": "The original name if it is already unique, or a unique version of the name.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Determines whether a view with the provided name already exists. If a view exists with the provided name, and new view is created with a unique name. Otherwise, the original view name is returned.\n\nView3D.CreateUniqueViewName (name: string): string"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Views.View.AddFilter@Revit.Filter.ParameterFilterElement",
      "Id": "8314d4f61a764299a2d5bb556270e357",
      "Inputs": [
        {
          "Id": "b7a10f4653b44807b261ec9e7658f6c6",
          "Name": "view",
          "Description": "Revit.Elements.Views.View",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "303107173f9a4eee8b678719d8cc2825",
          "Name": "parameterFilter",
          "Description": "Parameter filter\n\nParameterFilterElement",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "befd81b6aca74f7191dd6d5ed88870d1",
          "Name": "view",
          "Description": "View",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Add a Filter to a View. The Filter will be added even if View has a View Template applied, which normally would prevent user from adding Filters without first disabling or modifying the View Template.\n\nView.AddFilter (parameterFilter: ParameterFilterElement): View"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Views.View.SetCategoryOverrides@Revit.Elements.Category,Revit.Filter.OverrideGraphicSettings,bool",
      "Id": "556029c49f2346458b3f1a47849821f2",
      "Inputs": [
        {
          "Id": "b7130c55b5ca450d988a67df2e60126e",
          "Name": "view",
          "Description": "Revit.Elements.Views.View",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2a706c78cfd14b34967736ce8e38b005",
          "Name": "category",
          "Description": "Category\n\nCategory",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "9cf30d3b4fb94a4db74327ca90ab563b",
          "Name": "overrides",
          "Description": "Graphics Overrides Settings.\n\nOverrideGraphicSettings",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "541e6469346b4ae791fbbac8e3237cf1",
          "Name": "hide",
          "Description": "If True givent Category will be hidden.\n\nbool\nDefault value : false",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "ef0216a33f204b16b6d5b4a602ab1a43",
          "Name": "view",
          "Description": "View",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Set Category Overrides.\n\nView.SetCategoryOverrides (category: Category, overrides: OverrideGraphicSettings, hide: bool = false): View"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Views.View.SetFilterOverrides@Revit.Filter.ParameterFilterElement,Revit.Filter.OverrideGraphicSettings,bool",
      "Id": "692dd6f28f3349a785083644c7940908",
      "Inputs": [
        {
          "Id": "e0bb51fdbbf04e8b80fc4edc1a25c4d0",
          "Name": "view",
          "Description": "Revit.Elements.Views.View",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "cf3329a5744d441496dada29505d47ba",
          "Name": "parameterFilter",
          "Description": "Parameter Filter\n\nParameterFilterElement",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "4853e316a46b4e9d930cd6272ce5ef47",
          "Name": "overrides",
          "Description": "Graphic Overrides Settings\n\nOverrideGraphicSettings",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "929d4a5302304818ae8e9de17dd81a35",
          "Name": "hide",
          "Description": "If True given Filter will be hidden.\n\nbool\nDefault value : false",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "a9e7863139e2421d8b440ec51881423a",
          "Name": "view",
          "Description": "View",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Set Filter overrides. If View doesn't have specified Filter, it will be first added to the View and then its settings will be overriden. This behavior will persist even if View has a View Template applied which normally would prevent user from adding Filters without first disabling or modifying the View Template.\n\nView.SetFilterOverrides (parameterFilter: ParameterFilterElement, overrides: OverrideGraphicSettings, hide: bool = false): View"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Views.View.SetScale@int",
      "Id": "3e7aa6951ee3462b8ca16a8af0633351",
      "Inputs": [
        {
          "Id": "57ffa32d18c44ad28a9fa3d738fd1fd5",
          "Name": "view",
          "Description": "Revit.Elements.Views.View",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "d09745364c304a8cb28a0a9d7196adee",
          "Name": "scale",
          "Description": "View scale is the ration of true model size to paper size.\n\nint\nDefault value : 100",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "8595d76e07114e92b604e9682854c532",
          "Name": "view",
          "Description": "View",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Set View Scale\n\nView.SetScale (scale: int = 100): View"
    }
  ],
  "Connectors": [],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.1.0.7500",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Element.SetParameterByName",
        "Id": "b5e3174f3cc344979cbe1c4d14e20fac",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 2900.3123973479519,
        "Y": -659.50530810813484
      },
      {
        "ShowGeometry": true,
        "Name": "Room.ByLocation",
        "Id": "e2cbb0cbe31e47f0925ef0004d582cfa",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 3525.1774091826283,
        "Y": -537.39467920356
      },
      {
        "ShowGeometry": true,
        "Name": "Level.ByElevation",
        "Id": "fd4486da196b48998e703303ba3604aa",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 3227.8944455976566,
        "Y": -129.63178349268105
      },
      {
        "ShowGeometry": true,
        "Name": "Level.ByElevationAndName",
        "Id": "b0061c04fc8a43fabbfa0ba238e2aa1b",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 3230.3301969105387,
        "Y": -546.14496015506313
      },
      {
        "ShowGeometry": true,
        "Name": "Level.ByLevelAndOffset",
        "Id": "a451c166eeb345feac2311385445fade",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 3225.9473641802961,
        "Y": -419.33265336125993
      },
      {
        "ShowGeometry": true,
        "Name": "Level.ByLevelOffsetAndName",
        "Id": "ac70e6f04da74d7bb6a23ada2db04f50",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 3230.1489072262211,
        "Y": -293.635066302598
      },
      {
        "ShowGeometry": true,
        "Name": "Room.SetName",
        "Id": "f409b73bd4bb4eceb82aec3242e2c93f",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 2963.5781711491472,
        "Y": -192.46877368941352
      },
      {
        "ShowGeometry": true,
        "Name": "Room.SetNumber",
        "Id": "d2a42998df1344cba4cfb77457cc617e",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 2963.5781711491472,
        "Y": -69.571920510804091
      },
      {
        "ShowGeometry": true,
        "Name": "Parameter.ParameterByName",
        "Id": "4dfb48d0881642bc95f07f8d5257a0bb",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 3551.56060399574,
        "Y": -253.91433578399187
      },
      {
        "ShowGeometry": true,
        "Name": "Parameter.CreateProjectParameter",
        "Id": "1d23aac1c6d64936822a1a479e223b1f",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 3551.56060399574,
        "Y": -149.91433578399187
      },
      {
        "ShowGeometry": true,
        "Name": "Parameter.CreateProjectParameterForAllCategories",
        "Id": "8347ac530a7e4e85b82ed5a57246e6db",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 3551.56060399574,
        "Y": 58.085664216008126
      },
      {
        "ShowGeometry": true,
        "Name": "Parameter.CreateSharedParameter",
        "Id": "d9c9b5ee127c4b81aec6c09ba663b07c",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 3551.56060399574,
        "Y": 240.08566421600813
      },
      {
        "ShowGeometry": true,
        "Name": "Parameter.CreateSharedParameterForAllCategories",
        "Id": "e71598c943bc4ebda6bed47d77b96e74",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 3551.56060399574,
        "Y": 448.08566421600813
      },
      {
        "ShowGeometry": true,
        "Name": "Parameter.SetValue",
        "Id": "91cce361e63c4cd48af57e7a5bdfafcf",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 2930.5538468726404,
        "Y": -478.47354016684682
      },
      {
        "ShowGeometry": true,
        "Name": "Wall.ByCurveAndHeight",
        "Id": "beae8d060eda4bf481c32f18ad8a03eb",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 3223.0475344917436,
        "Y": 79.3292786329439
      },
      {
        "ShowGeometry": true,
        "Name": "Wall.ByCurveAndLevels",
        "Id": "53dccb613363435da79f33b702f9a6e8",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 3222.8172037851773,
        "Y": 267.33489550780541
      },
      {
        "ShowGeometry": true,
        "Name": "Sheet.ByNameNumberTitleBlockAndView",
        "Id": "0fcea3e831214deeae8ff01e8c132302",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 2874.681709799188,
        "Y": 170.58875460288817
      },
      {
        "ShowGeometry": true,
        "Name": "Sheet.ByNameNumberTitleBlockAndViews",
        "Id": "b0767bb0d4f5475d8ac16647e35f7804",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 2873.3583996266825,
        "Y": 341.29576685614865
      },
      {
        "ShowGeometry": true,
        "Name": "AreaPlanView.ByLevelAndAreaScheme",
        "Id": "3264028964ff4624a2e2293bc661c765",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 4017.1338938076624,
        "Y": -561.57152996453544
      },
      {
        "ShowGeometry": true,
        "Name": "AxonometricView.ByEyePointAndTarget",
        "Id": "0cfc0dad6a8646cdabbcb1f33350c01f",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 4017.1338938076624,
        "Y": -41.571529964535443
      },
      {
        "ShowGeometry": true,
        "Name": "AxonometricView.ByEyePointTargetAndBoundingBox",
        "Id": "ecf3cf97b31e453c8c3e5754aacaf395",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 4017.1338938076624,
        "Y": 374.42847003546456
      },
      {
        "ShowGeometry": true,
        "Name": "AxonometricView.ByEyePointTargetAndElement",
        "Id": "aa705ca1aa414508a4bc51518b1e5e11",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 4017.1338938076624,
        "Y": 816.42847003546456
      },
      {
        "ShowGeometry": true,
        "Name": "CeilingPlanView.ByLevel",
        "Id": "c7349a20edd44714826f59e10e481702",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 4017.1338938076624,
        "Y": -457.57152996453544
      },
      {
        "ShowGeometry": true,
        "Name": "DraftingView.ByName",
        "Id": "16b74724d86742b6b6256e36c0acb5d6",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 4017.1338938076624,
        "Y": -197.57152996453544
      },
      {
        "ShowGeometry": true,
        "Name": "FloorPlanView.ByLevel",
        "Id": "bf37965bc34342adb321d9372c132695",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 4017.1338938076624,
        "Y": 88.428470035464557
      },
      {
        "ShowGeometry": true,
        "Name": "PerspectiveView.ByEyePointAndTarget",
        "Id": "f2dd359798264ebeab9e8c4fbc0022e6",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 4017.1338938076624,
        "Y": 556.42847003546478
      },
      {
        "ShowGeometry": true,
        "Name": "PerspectiveView.ByEyePointTargetAndBoundingBox",
        "Id": "1d7ab1ee5d3b4b568c3cb38c1007e527",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 4017.1338938076624,
        "Y": 998.42847003546456
      },
      {
        "ShowGeometry": true,
        "Name": "PerspectiveView.ByEyePointTargetAndElement",
        "Id": "033ddb9d9f3f404081b13142d4c4ac2b",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 4017.1338938076624,
        "Y": -379.57152996453544
      },
      {
        "ShowGeometry": true,
        "Name": "SectionView.ByBoundingBox",
        "Id": "781520ee127a40caa92c5e9e34f39012",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 4017.1338938076624,
        "Y": -119.57152996453544
      },
      {
        "ShowGeometry": true,
        "Name": "SectionView.ByCoordinateSystemMinPointMaxPoint",
        "Id": "46b04a41a44e4871a83e188ecf4befc8",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 4017.1338938076624,
        "Y": 166.42847003546456
      },
      {
        "ShowGeometry": true,
        "Name": "StructuralPlanView.ByLevel",
        "Id": "f9e81c00248b488597690fbd5df0d8f7",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 4017.1338938076624,
        "Y": 296.42847003546456
      },
      {
        "ShowGeometry": true,
        "Name": "View3D.CreateUniqueViewName",
        "Id": "7ee41da73d784b0a917fd73cc889fabf",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 4017.1338938076624,
        "Y": 738.42847003546478
      },
      {
        "ShowGeometry": true,
        "Name": "View.AddFilter",
        "Id": "8314d4f61a764299a2d5bb556270e357",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 4496.0729070716989,
        "Y": -171.46167854063242
      },
      {
        "ShowGeometry": true,
        "Name": "View.SetCategoryOverrides",
        "Id": "556029c49f2346458b3f1a47849821f2",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 4491.3750593699569,
        "Y": -514.75477318569574
      },
      {
        "ShowGeometry": true,
        "Name": "View.SetFilterOverrides",
        "Id": "692dd6f28f3349a785083644c7940908",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 4491.9681215795672,
        "Y": -341.33246028105054
      },
      {
        "ShowGeometry": true,
        "Name": "View.SetScale",
        "Id": "3e7aa6951ee3462b8ca16a8af0633351",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 4489.3493715820314,
        "Y": -42.390783133799459
      }
    ],
    "Annotations": [
      {
        "Id": "4ca78d82de474456bfab1342e7586eee",
        "Title": "Write to Revit: Create parameters",
        "Nodes": [],
        "Left": 3541.56060399574,
        "Top": -511.91433578399187,
        "Width": 0.0,
        "Height": 0.0,
        "FontSize": 36.0,
        "InitialTop": 0.0,
        "InitialHeight": 0.0,
        "TextblockHeight": 0.0,
        "Background": "#FFC1D676"
      },
      {
        "Id": "308ae260dbf447a4a2059290894bfa77",
        "Title": "Write to Revit: Create views",
        "Nodes": [],
        "Left": 4007.1338938076624,
        "Top": -77.571529964535216,
        "Width": 0.0,
        "Height": 0.0,
        "FontSize": 36.0,
        "InitialTop": 0.0,
        "InitialHeight": 0.0,
        "TextblockHeight": 0.0,
        "Background": "#FFC1D676"
      }
    ],
    "X": -743.824745207026,
    "Y": 281.624668122038,
    "Zoom": 0.38153547064518956
  }
}