{
  "Uuid": "3c9d0464-8643-5ffe-96e5-ab1769818209",
  "IsCustomNode": false,
  "Description": "",
  "Name": "CANOPY_PROJECT",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Nodes.DSModelElementsSelection, DSRevitNodesUI",
      "NodeType": "ExtensionNode",
      "InstanceId": [],
      "Id": "ea68c0dd6a9842da92f2164cf2376999",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "21fc8e5a823f4a4c8dbab95e249620cb",
          "Name": "Elements",
          "Description": "The selected elements.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Grid.Curve",
      "Id": "b75e54d9c41a4c1eae19f35ecdcefd86",
      "Inputs": [
        {
          "Id": "edf5facb50df4f30b28458c0026ae006",
          "Name": "grid",
          "Description": "Revit.Elements.Grid",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "cfcec355ffb846ceaab9e64f3b7bea94",
          "Name": "Curve",
          "Description": "Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the underlying Curve geometry from this Element\n\nGrid.Curve: Curve"
    },
    {
      "ConcreteType": "Dynamo.Nodes.DSFaceSelection, DSRevitNodesUI",
      "NodeType": "ExtensionNode",
      "InstanceId": [],
      "Id": "981c382649864c6b930d07080492d495",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "a4d519ed21d4421688c3082c2aee7c5d",
          "Name": "Surface",
          "Description": "The selected elements.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Surface.ProjectInputOnto@Autodesk.DesignScript.Geometry.Geometry,Autodesk.DesignScript.Geometry.Vector",
      "Id": "d03944486c234929bc04526ecd6ccc05",
      "Inputs": [
        {
          "Id": "2846bcad20e94560a82758444fcd5123",
          "Name": "surface",
          "Description": "Autodesk.DesignScript.Geometry.Surface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f672b486d63b41a08f8511c36ed94169",
          "Name": "geometryToProject",
          "Description": "Geometry",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "963bec6e8a724464872050cb832ff8d2",
          "Name": "projectionDirection",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "2bfc4ca0cc104e289166c7418c9563bf",
          "Name": "Geometry[]",
          "Description": "Geometry[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Longest",
      "Description": "Projects the input Geometry onto this Surface in the input Vector direction\n\nSurface.ProjectInputOnto (geometryToProject: Geometry, projectionDirection: Vector): Geometry[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Vector.ZAxis",
      "Id": "eb8acb75229d4ec1ad59c3d8c8d5fa38",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "7a07670b56bf45d4ae7ad74002885f97",
          "Name": "Vector",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the canonical Z axis Vector (0,0,1)\n\nVector.ZAxis ( ): Vector"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.StructuralFraming.BeamByCurve@Autodesk.DesignScript.Geometry.Curve,Revit.Elements.Level,Revit.Elements.FamilyType",
      "Id": "45674337ea474a97a5429fa302e56961",
      "Inputs": [
        {
          "Id": "31220d4627f046648446dd63d5482ebd",
          "Name": "curve",
          "Description": "The curve which defines the center line of the beam.\n\nCurve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "91783008d8b0430b91d541b61b983c0b",
          "Name": "level",
          "Description": "The level with which you'd like the beam to be associated.\n\nLevel",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "6435abc1718946b4851ecb75e798185e",
          "Name": "structuralFramingType",
          "Description": "The structural framing type representing the beam.\n\nFamilyType",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "bd40c32058ce42cab7664d4f2a06b1d1",
          "Name": "StructuralFraming",
          "Description": "StructuralFraming",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a beam.\n\nStructuralFraming.BeamByCurve (curve: Curve, level: Level, structuralFramingType: FamilyType): StructuralFraming"
    },
    {
      "ConcreteType": "DSRevitNodesUI.StructuralFramingTypes, DSRevitNodesUI",
      "SelectedIndex": -1,
      "NodeType": "ExtensionNode",
      "Id": "3f67a0449bf14c73a1c1ab0f797b31ed",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "54c78d16944a43d98b3767e042928f30",
          "Name": "Framing Types",
          "Description": "The selected Framing Types",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Select a structural framing type in the active document"
    },
    {
      "ConcreteType": "DSRevitNodesUI.Levels, DSRevitNodesUI",
      "SelectedIndex": 4,
      "NodeType": "ExtensionNode",
      "Id": "be6da7035f8e47eebf9b4b56cbbe270f",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "becbd3857b7b48629ac9391d94991c1c",
          "Name": "Levels",
          "Description": "The selected Levels",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Select a level in the active document"
    }
  ],
  "Connectors": [
    {
      "Start": "21fc8e5a823f4a4c8dbab95e249620cb",
      "End": "edf5facb50df4f30b28458c0026ae006",
      "Id": "8f8b417182464fcda1a2029993685a3d"
    },
    {
      "Start": "cfcec355ffb846ceaab9e64f3b7bea94",
      "End": "f672b486d63b41a08f8511c36ed94169",
      "Id": "0a319d6edfee44eb98c7a9ee0e785d66"
    },
    {
      "Start": "a4d519ed21d4421688c3082c2aee7c5d",
      "End": "2846bcad20e94560a82758444fcd5123",
      "Id": "e57c465306ef4437b3b714e73f0f6ae5"
    },
    {
      "Start": "2bfc4ca0cc104e289166c7418c9563bf",
      "End": "31220d4627f046648446dd63d5482ebd",
      "Id": "d2654879fb2a4b09ad519545c558e8e7"
    },
    {
      "Start": "7a07670b56bf45d4ae7ad74002885f97",
      "End": "963bec6e8a724464872050cb832ff8d2",
      "Id": "87d837e5ce504f0a8ce6b4135236e947"
    },
    {
      "Start": "54c78d16944a43d98b3767e042928f30",
      "End": "6435abc1718946b4851ecb75e798185e",
      "Id": "68e864dff7ef480ea1e1973f20bf5581"
    },
    {
      "Start": "becbd3857b7b48629ac9391d94991c1c",
      "End": "91783008d8b0430b91d541b61b983c0b",
      "Id": "da7a83439a9e47edb3b0882bcdc9c765"
    }
  ],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.0.2.6826",
      "RunType": "Automatic",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -8.6835403442382812,
      "EyeY": 56.006782531738281,
      "EyeZ": 17.127063751220703,
      "LookX": -26.160030364990234,
      "LookY": -23.087400436401367,
      "LookZ": -49.5946044921875,
      "UpX": -0.0810156911611557,
      "UpY": 0.98480772972106934,
      "UpZ": -0.1535908430814743
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Select Model Elements",
        "Id": "ea68c0dd6a9842da92f2164cf2376999",
        "IsSetAsInput": true,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 50.0,
        "Y": 300.0
      },
      {
        "ShowGeometry": true,
        "Name": "Grid.Curve",
        "Id": "b75e54d9c41a4c1eae19f35ecdcefd86",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 348.0,
        "Y": 302.0
      },
      {
        "ShowGeometry": true,
        "Name": "Select Face",
        "Id": "981c382649864c6b930d07080492d495",
        "IsSetAsInput": true,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 47.0,
        "Y": 166.0
      },
      {
        "ShowGeometry": true,
        "Name": "Surface.ProjectInputOnto",
        "Id": "d03944486c234929bc04526ecd6ccc05",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 567.0,
        "Y": 173.0
      },
      {
        "ShowGeometry": true,
        "Name": "Vector.ZAxis",
        "Id": "eb8acb75229d4ec1ad59c3d8c8d5fa38",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 570.0,
        "Y": 310.0
      },
      {
        "ShowGeometry": true,
        "Name": "StructuralFraming.BeamByCurve",
        "Id": "45674337ea474a97a5429fa302e56961",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1079.0,
        "Y": 182.0
      },
      {
        "ShowGeometry": true,
        "Name": "Structural Framing Types",
        "Id": "3f67a0449bf14c73a1c1ab0f797b31ed",
        "IsSetAsInput": true,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 892.0,
        "Y": 323.0
      },
      {
        "ShowGeometry": true,
        "Name": "Levels",
        "Id": "be6da7035f8e47eebf9b4b56cbbe270f",
        "IsSetAsInput": true,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 895.0,
        "Y": 225.0
      }
    ],
    "Annotations": [],
    "X": -10.0,
    "Y": -18.0,
    "Zoom": 1.0
  }
}