{
  "Uuid": "3c9d0464-8643-5ffe-96e5-ab1769818209",
  "IsCustomNode": false,
  "Description": "",
  "Name": "SURFACE_SINGLE_POINTATPARAMETER_01",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Rectangle.ByWidthLength@double,double",
      "Id": "9655317d0f2541959234a3b64b4dca84",
      "Inputs": [
        {
          "Id": "a670c76e7793453cb4edb309dbee6ac2",
          "Name": "width",
          "Description": "double\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "bc2817c6caaa473fa955d681cf472664",
          "Name": "length",
          "Description": "double\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "3071b8b2a23a48fdb34e85679588ca17",
          "Name": "Rectangle",
          "Description": "Rectangle",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Rectangle centered at the WCS origin in the WCS XY Plane, with specified width (X Axis length), and length (Y Axis length).\n\nRectangle.ByWidthLength (width: double = 1, length: double = 1): Rectangle"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Surface.ByPatch@Autodesk.DesignScript.Geometry.Curve",
      "Id": "f9c311c1add643b1a6ec85202972744e",
      "Inputs": [
        {
          "Id": "192203d35f37465295129015c4fe9c90",
          "Name": "closedCurve",
          "Description": "Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "3ef33a4abc8649fa847eac77eb546991",
          "Name": "Surface",
          "Description": "Surface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Surface by filling in the interior of a closed boundary defined by input Curves.\n\nSurface.ByPatch (closedCurve: Curve): Surface"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Surface.PointAtParameter@double,double",
      "Id": "65a4cf95b1404da8866ef1f4fee08c03",
      "Inputs": [
        {
          "Id": "55da5c21b2c74cc4ba8cfa065fa414fd",
          "Name": "surface",
          "Description": "Autodesk.DesignScript.Geometry.Surface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "486e714795084bf686ae703dc2e5dee6",
          "Name": "u",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "67a4c825f2044f62b1c3d00634db2a66",
          "Name": "v",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "b44c239376dd44488cc3979ffb463b0d",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Return the Point at specified U and V parameters.\n\nSurface.PointAtParameter (u: double = 0, v: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "0;\n1;",
      "Id": "2ef1697322f84b49b4d45f535924a43d",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "825762164dff407cb3094e8573ffe302",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "d69efbcd592b412c9e0df982cac16f63",
          "Name": "",
          "Description": "Value of expression at line 2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    }
  ],
  "Connectors": [
    {
      "Start": "3071b8b2a23a48fdb34e85679588ca17",
      "End": "192203d35f37465295129015c4fe9c90",
      "Id": "21eae5b9adc04c0bb143b50153c7167e"
    },
    {
      "Start": "3ef33a4abc8649fa847eac77eb546991",
      "End": "55da5c21b2c74cc4ba8cfa065fa414fd",
      "Id": "ae59ef825a4a43e9937218955ae0a8ce"
    },
    {
      "Start": "825762164dff407cb3094e8573ffe302",
      "End": "486e714795084bf686ae703dc2e5dee6",
      "Id": "5feb60d0946e487ca20b5129cec5a124"
    },
    {
      "Start": "d69efbcd592b412c9e0df982cac16f63",
      "End": "67a4c825f2044f62b1c3d00634db2a66",
      "Id": "9d7ca3589cc547e892c48520eabab278"
    }
  ],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.0.2.6826",
      "RunType": "Automatic",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": 1.0640277862548828,
      "EyeY": 1.5185257196426392,
      "EyeZ": 0.6248164176940918,
      "LookX": -4.6100192070007324,
      "LookY": -5.1551394462585449,
      "LookZ": -2.736072301864624,
      "UpX": -0.44932106137275696,
      "UpY": 0.85264015197753906,
      "UpZ": -0.26667457818984985
    },
    "NodeViews": [
      {
        "ShowGeometry": false,
        "Name": "Rectangle.ByWidthLength",
        "Id": "9655317d0f2541959234a3b64b4dca84",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 299.241760066262,
        "Y": 577.99279283499
      },
      {
        "ShowGeometry": true,
        "Name": "Surface.ByPatch",
        "Id": "f9c311c1add643b1a6ec85202972744e",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 292.653019448316,
        "Y": 498.104516586346
      },
      {
        "ShowGeometry": true,
        "Name": "Surface.PointAtParameter",
        "Id": "65a4cf95b1404da8866ef1f4fee08c03",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 662.283601195263,
        "Y": 498.261941108841
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "2ef1697322f84b49b4d45f535924a43d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 552.783284791177,
        "Y": 531.065003589865
      }
    ],
    "Annotations": [],
    "X": -380.078343060115,
    "Y": -966.210134419545,
    "Zoom": 1.97667628894291
  }
}