{
  "Uuid": "3c9d0464-8643-5ffe-96e5-ab1769818209",
  "IsCustomNode": false,
  "Description": "",
  "Name": "SURFACE_BY_CURVE_EXTRUDE",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "32f7af03377940db9b9eff065528c53a",
      "Inputs": [
        {
          "Id": "7913f75622704cfd9353618fd470935d",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "cd07f71b9072465da89d4bc0e9e5c35f",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f7017440a02e42bb8f324202be8bd5e9",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "626b21ad0b4a4b6bb5c6b4643b7e35bd",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "1;",
      "Id": "ef3577e9f89e482f8b8ca9849dfbbe09",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "08661dfe374244b8a8f61564a9953355",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Id": "f3e5db5f18a54d2692b3a2b03f154d18",
      "Inputs": [
        {
          "Id": "f6f5716f638d4f13b1b2273b2f785f77",
          "Name": "startPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "efa41042cda944df9c73bace0eb11af9",
          "Name": "endPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "c8daca21308a403abe7b91771467a290",
          "Name": "Line",
          "Description": "Line",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Creates a straight Line between two input Points.\n\nLine.ByStartPointEndPoint (startPoint: Point, endPoint: Point): Line"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "bc7312386a6a46fb8e6043f546843245",
      "Inputs": [
        {
          "Id": "f2b8df6560ba41a8af5e1f6c9bc053dd",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "12a5527e7143493189569dd6a244abb9",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "9efb717dc7f6439f8f1acc0d1487024b",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "582a7a6a79f1477a89b42fbe72aea162",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.Extrude@double",
      "Id": "3a70a1ff25c549129af70c176b69ae1d",
      "Inputs": [
        {
          "Id": "f0002c63d93445d088ec1eab0529299f",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "cd9d5b82724b43bbb3db5959e4d7d4a9",
          "Name": "distance",
          "Description": "The distance to extrude the curve\n\ndouble\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "c193b733680a4afb99f4012d09d9c80b",
          "Name": "Surface",
          "Description": "The extruded Surface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Extrudes a Curve in the normal Vector direction\n\nCurve.Extrude (distance: double = 1): Surface"
    }
  ],
  "Connectors": [
    {
      "Start": "626b21ad0b4a4b6bb5c6b4643b7e35bd",
      "End": "f6f5716f638d4f13b1b2273b2f785f77",
      "Id": "9c8e3ee82463437185a35391b73b7b93"
    },
    {
      "Start": "08661dfe374244b8a8f61564a9953355",
      "End": "7913f75622704cfd9353618fd470935d",
      "Id": "0ea8b61e708b41579783970c08bbf21c"
    },
    {
      "Start": "c8daca21308a403abe7b91771467a290",
      "End": "f0002c63d93445d088ec1eab0529299f",
      "Id": "6424a00de2d04582ab5240f2f399fd02"
    },
    {
      "Start": "582a7a6a79f1477a89b42fbe72aea162",
      "End": "efa41042cda944df9c73bace0eb11af9",
      "Id": "e7edb68890c14e8382cfec89cd0acf5c"
    }
  ],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.0.2.6826",
      "RunType": "Automatic",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": 2.6391220092773438,
      "EyeY": 2.7473375797271729,
      "EyeZ": 6.4564681053161621,
      "LookX": -10.663468360900879,
      "LookY": -0.88483309745788574,
      "LookZ": -7.5192866325378418,
      "UpX": 0.12079751491546631,
      "UpY": 0.98901587724685669,
      "UpZ": 0.085179708898067474
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "32f7af03377940db9b9eff065528c53a",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 269.652692219674,
        "Y": 573.286506909774
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "ef3577e9f89e482f8b8ca9849dfbbe09",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 148.09799782362,
        "Y": 600.033761915214
      },
      {
        "ShowGeometry": true,
        "Name": "Line.ByStartPointEndPoint",
        "Id": "f3e5db5f18a54d2692b3a2b03f154d18",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 624.450898340627,
        "Y": 585.472755549536
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "bc7312386a6a46fb8e6043f546843245",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 437.938377148942,
        "Y": 472.23119602834
      },
      {
        "ShowGeometry": true,
        "Name": "Curve.Extrude",
        "Id": "3a70a1ff25c549129af70c176b69ae1d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 888.979170266723,
        "Y": 584.725500544095
      }
    ],
    "Annotations": [],
    "X": -36.0712687499999,
    "Y": -514.4095,
    "Zoom": 1.33823125
  }
}